name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11

      - uses: eskatos/gradle-command-action@v1
        name: Fetch Dependencies
        with:
          arguments: dependencies

      - uses: eskatos/gradle-command-action@v1
        name: Assemble
        with:
          arguments: assemble

      - uses: eskatos/gradle-command-action@v1
        name: Tests
        with:
          # TODO: set the properties correctly
          arguments: >
            test
            -Pdatalbry.connector.property1.${{ secrets.TODO_CHANGE_ME }} 
            -Pdatalbry.connector.property2.${{ secrets.TODO_CHANGE_ME }}
            -Pdatalbry.connector.property3.${{ secrets.TODO_CHANGE_ME }}

