name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MAVEN_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USER }}
  MAVEN_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
  # TODO: Change the next lines
  EXAMPLE_PROPERTY_A: ${{ secrets.EXAMPLE_PROPERTY_A }}
  EXAMPLE_PROPERTY_B: ${{ secrets.EXAMPLE_PROPERTY_B }}
  EXAMPLE_PROPERTY_C: ${{ secrets.EXAMPLE_PROPERTY_C }}

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - uses: eskatos/gradle-command-action@v1
        name: Fetch Dependencies
        with:
          arguments: dependencies

      - uses: eskatos/gradle-command-action@v1
        name: Assemble
        with:
          arguments: assemble

      - uses: eskatos/gradle-command-action@v1
        name: Tests
        with:
          arguments: test
