name: Release Documentation

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    paths:
      - "templates/docs/*"

env:
  API_TOKEN_GITHUB: ${{ secrets.CI_TOKEN }}
  MAVEN_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USER }}
  MAVEN_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: eskatos/gradle-command-action@v1
        name: Update Documentation
        with:
          arguments: prepareDocs

      - name: Generate Connector Name
        run: |
          echo "$(./gradlew -q printVersion)"
        id: generate_connector_name

      - name: Release Documentation
        uses: datalbry/copy_folder_to_another_repo_action@1.0.1
        with:
          source_folder: 'docs'
          destination_repo: 'datalbry/docs'
          destination_folder: 'docs/Connectors/${{steps.generate_connector_name.outputs.message}}'
          destination_branch: 'main'
          user_email: ${{ secrets.CI_EMAIL }}
          user_name: ${{ secrets.CI_USERNAME }}
          commit_msg: '[CI:${{steps.generate_connector_name.outputs.message}}] Release documentation'
