name: Release Beta

on:
  workflow_dispatch:

env:
  MAVEN_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USER }}
  MAVEN_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}
  # TODO: Change the next lines
  DATALBRY_SOME_CONNECTOR_PROPERTY_ONE: ${{ secrets.DATALBRY_SOME_CONNECTOR_PROPERTY_ONE }}
  DATALBRY_SOME_CONNECTOR_PROPERTY_TWO: ${{ secrets.DATALBRY_SOME_CONNECTOR_PROPERTY_TWO }}
  DATALBRY_SOME_CONNECTOR_PROPERTY_THREE: ${{ secrets.DATALBRY_SOME_CONNECTOR_PROPERTY_THREE }}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11

      - id: install-secret-key
        name: Install GnuPG Key
        run: |
          cat <(echo -e "${{ secrets.GNUPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Update Version
        run: >
          ./gradlew updateBetaVersion -i

      - uses: eskatos/gradle-command-action@v1
        name: Fetch Dependencies
        with:
          arguments: dependencies

      - uses: eskatos/gradle-command-action@v1
        name: Push container image
        with:
          arguments: >
            jib
            -Pconnector.container.username=${{ secrets.CONTAINER_REGISTRY_USER }}
            -Pconnector.container.password=${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - uses: eskatos/gradle-command-action@v1
        name: Register in Connector Registry
        with:
          arguments: >
            registerConnector
            -Pconnector.oidc.clientSecret=${{ secrets.CONNECTOR_REGISTRY_CLIENT_SECRET }}
            -Pconnector.oidc.username=${{ secrets.CONNECTOR_CI_USER }}
            -Pconnector.oidc.password=${{ secrets.CONNECTOR_CI_PASSWORD }}

      - name: Tag
        run: >
          ./gradlew tag -i

      - name: Generate Commit Message
        run: |
          echo "##[set-output name=message;][CI] Release version $(./gradlew -q printVersion)"
        id: generate_commit_message

      - name: Push Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.generate_commit_message.outputs.message }}
          push_options: --follow-tags
