= DataLbry Connector SDK Concepts

The Connector SDK is written with a few core-concepts in mind.
In this section we will go through all of them to give you a better understanding of what the SDK is doing under the hood.

== Concept: Nodes and Edges
The Connector SDK is written with a graph in mind, which have to mapped into the Code itself.
The graph describes the data source and all of its data.

=== Edge
Edges are describing how the connector can obtain another set of data.
It's basically the information we require to traverse the system further.

=== Node
Nodes are basically information of the system, they can contain further edges, as well as documents.

NOTE: If you are unfamiliar with concepts of Documents and Precise, please checkout the link:TODO[wiki].

For our example we are using a Filesystem Connector, which simply goes through a local filesystem.
A filesystem commonly consists of `Files` and `Directories`. The rules are simple, a Directory contains links to other directories and to files. A file cannot link to another file or any directory.

[plantuml, filesystem, png]
----
@startuml
digraph g {
    size="8,5"
    Directory -> Directory    [label = "1:n"];
    Directory -> File    [label = "1:n"];
}
@enduml
----
