= DataLbry Connector SDK Overview

The Connector SDK is a Software Development Kit for JVM based Connector applications for the DataLbry Knowledge Cloud.
Enabling developer to easily integrate any kind of data source.

It is highly based on automation, such as Schema generation for Document schema and Configuration schema.
The Connector SDK is developed with a UI integration in mind,
making it easy to run automatically in the DataLbry Knowledge Cloud without the Developer bothering all too much.

== What we mean by `Connector`
A Connector is an application which fetches data from a source system, transforms it and puts it into a target system.
This is rather abstract, but as an example a Connector can fetch documents, such as Spaces, Pages, Attachments, Persons and more from Confluence
and puts it into a database such as Postgres.
The DataLbry Connector-SDK always puts the data into the DataLbry Knowledge Cloud,
which is fully handled by the SDK itself and has not to be implemented by the user.




