name: CI

on:
  pull_request:
    branches: [ main ]

env:
  MAVEN_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USER }}
  MAVEN_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: eskatos/gradle-command-action@v1
        name: Fetch Dependencies
        with:
          arguments: dependencies

      - uses: eskatos/gradle-command-action@v1
        name: Assemble
        with:
          arguments: assemble

      - uses: eskatos/gradle-command-action@v1
        name: Tests
        with:
          arguments: test
