name: Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the Release'
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Set selected color
        run: echo 'Version "&{{ github.event.inputs.version }}"'

      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11
          
      - uses: eskatos/gradle-command-action@v1
        name: Fetch Dependencies
        with:
          arguments: dependencies
          
      - uses: eskatos/gradle-command-action@v1
        name: Assemble
        with:
          arguments: assemble
          
      - uses: eskatos/gradle-command-action@v1
        name: Tests
        with:
          arguments: test

  Release-Snapshot:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.event.inputs.version == '' }}
    needs: build

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11

      - id: install-secret-key
        name: Install GnuPG Key
        run: |
          cat <(echo -e "${{ secrets.GNUPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          
      - uses: eskatos/gradle-command-action@v1
        name: Release (Snapshot)
        with:
          arguments: >
            publishMavenPublicationToSonatypeRepository
            -Psnapshot=true
            -PsonatypeUsername=${{ secrets.MAVENCENTRALUSERNAME }}
            -PsonatypePassword=${{ secrets.MAVENCENTRALPASSWORD }}
            -Psigning.gnupg.keyName=${{ secrets.GNUPG_SECRET_NAME }}
            -Psigning.gnupg.passphrase=${{ secrets.GNUPG_SECRET_PASSWORD }}
