name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: dependencies
          
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble
          
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: test
          
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishSnapshotPublicationToSonatypeRepository
        env: # Or as an environment variable
          sonatypeUsername: ${{ secrets.SonatypeUsername }}
          sonatypePassword: ${{ secrets.SonatypePassword }}
          signing.gnupg.keyName: ${{ secrets.GnupgKeyname }}
          signing.gnupg.passphrase: ${{ secrets.GnupgPassphrase }}
