name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11
          
      - uses: eskatos/gradle-command-action@v1
        name: Fetch Dependencies
        with:
          arguments: dependencies
          
      - uses: eskatos/gradle-command-action@v1
        name: Assemble
        with:
          arguments: assemble
          
      - uses: eskatos/gradle-command-action@v1
        name: Tests
        with:
          arguments: test
          
      - id: install-secret-key
        name: Install GnuPG Key
        run: |
          cat <(echo -e "${{ secrets.GNUPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
          
      - uses: eskatos/gradle-command-action@v1
        name: Release (Snapshot)
        with:
          arguments: publishMavenPublicationToSonatypeRepository -PreleaseSnapshot=true
        env:
          sonatypeUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          sonatypePassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          signing.gnupg.keyName: ${{ secrets.GNUPG_SECRET_NAME }}
          signing.gnupg.passphrase: ${{ secrets.GNUPG_SECRET_PASSWORD }}
          
