name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the Release'
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-java@v1
        name: Setup Java
        with:
          java-version: 11

      - uses: eskatos/gradle-command-action@v1
        name: Fetch Dependencies
        with:
          arguments: dependencies

      - uses: eskatos/gradle-command-action@v1
        name: Assemble
        with:
          arguments: assemble

      - uses: eskatos/gradle-command-action@v1
        name: Tests
        with:
          arguments: test

